# Generated by Django 2.2.5 on 2019-11-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='num_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
