# Generated by Django 2.2.5 on 2019-11-17 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_review_num_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='num_reviews',
        ),
    ]
