# Generated by Django 2.2.5 on 2019-12-10 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='num_reviews',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
